# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: vsrmmt123
# "service" is the name of this project. This will also be added to your AWS resource names.
service: lambda-receiver-eventbg

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

functions:
  EBReceiverLambda:
    handler: recHandler.receiveEvent
    events:
      - eventBridge:
          useCloudFormation: true
          eventBus: !Ref ReceiverEventBus
          pattern:
            source:
              - my.application
            detail-type:
              - MyCustomDetail

resources:
  Resources:
    # This is the receiving invoice processing event bus in account C.
    ReceiverEventBus: 
      Type: AWS::Events::EventBus
      Properties: 
        Name: my-receiver-eb
    
    ReceiverEventBusPolicy: 
      Type: AWS::Events::EventBusPolicy
      Properties:
          EventBusName: !Ref ReceiverEventBus
          StatementId: ReceiverEventBusPolicyForCrossAccount
          Statement: 
              Effect: Allow
              # assign role of sender eventbus as principal
              Principal: 
                  AWS: arn:aws:iam::233886345769:role/vsr-sender-acc-eb-role-PROD
              Action: 
                  - events:PutEvents
              Resource: !GetAtt ReceiverEventBus.Arn